{% set name = "seqfu" %}
{% set version = "TODO" %}
{% set sha256hash = "TODO" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/telatin/porfast/archive/v{{ version }}.tar.gz
    sha256: {{ sha256hash }}
  - url: https://nim-lang.org/download/nim-1.2.0.tar.xz
    sha256: 4e94583a373965821805e665e0a05f52fb610916676edb09148941415637c575
    folder: nim_source

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - nim
  host:
    - zlib
    
test:
  commands:
    - seqfu --help
    - seqfu stats --help
    - ./bin/seqfu  --version | grep "version: {{ version }}"

about:
  home: https://github.com/telatin/seqfu2
  license: MIT
  summary: 'Suite of utilities to manipulate FASTA/FASTQ files.'