title: SeqFu docs
repository: telatin/seqfu2
lang: en
description: "SeqFu - FASTX Sequence Utilities"

readme_index:
  with_frontmatter: true

theme: null

remote_theme:  telatin/docs-theme 

plugins:
  - jekyll-remote-theme
  - jemoji

markdown: CommonMarkGhPages
commonmark:
  options: ['SMART']
  extensions: ['table']

scss: |
  .header     { background: #44435C}
  .markdown-body a { color: #46077d}
  .markdown-body a:hover { color: #7c39b7}
  .toctree>ul>.toc:not(.current)>a:active  {background: #6c1b7a}
  a { color: #34334C}
  .toasts.note .title { background: #caaaf2 }
  .toasts.note { background: #DFE2E5 }
  .text-blue { color: #8e8e8e !important }
