title: seqfu2
repository: telatin/seqfu2
lang: en
description: "seqfu2: fastx sequence utilities"

readme_index:
  with_frontmatter: true

theme: null

remote_theme: rundocs/jekyll-rtd-theme

plugins:
  - jekyll-remote-theme

markdown: CommonMarkGhPages
commonmark:
  options: ['SMART']
  extensions: ['table']

scss: |
  $theme-blue: #44435C;
