# This is a basic workflow to help you get started with Actions

name: Seqfu-Release

# Controls when the workflow will run
on:
  release:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Nim environment
        # You may pin to the exact commit or the version.
        # uses: jiro4989/setup-nim-action@5bbc93d889ba575ed95cde254faa197193690456
        uses: jiro4989/setup-nim-action@v1.1.4
        with:
          # The Nim version to download (if necessary) and use. Example: 1.0.2
          nim-version: 1.6.6
      - run: nimble build --passL:-lz -d:useLibzipSrc -d:release --opt:speed -Y
      - run: chmod +x ./scripts/* && cp -v ./scripts/* ./bin/
      - run:  export PATH="$PATH":bin/ && bin/seqfu version && bash test/mini.sh
      - name: Generate terminal images with rich-codex
        uses: ewels/rich-codex@v1
        with:
          commit_changes: "true"
